label ch2_p1:
    #scene 2
    stop music fadeout .5
    scene bg residential_day
    with dissolve_scene_full
    "I step outside and am immediately greeted by an energetic second-year student."
    play music wn14
    show rikka 1u at t11
    $ r_name = "Rikka"
    r "Good morning, [player]."
    mc "Hello, Rikka."
    r 1a "How'd you sleep last night?"
    mc "Eh."
    r 1c "Are you still having trouble falling asleep?"
    "I just shrug."
    "Rikka's been walking to school with me for the past week or so."
    "Sayori has been sick at home, and she specifically requested we let her be while she recovers."
    "Because of this, Rikka has taken it upon herself to fill in for Sayori in a way."
    "Including trying to be my best friend, which obviously is a little different for Rikka than it is for Sayori."
    r 1a "Well, did you at least have time to eat breakfast this morning?"
    mc "Yep. I had some yogurt."
    r 1c "[player], yogurt by itself isn't breakfast."
    mc "Yes it is. I ate it to break my fast. Therefore, it is breakfast."
    r 1z "Whatever you say."
    show rikka at thide
    hide rikka
    "As soon as we start walking to school, I get a cold chill."
    "Rikka notices and gives me a concerned look."
    show rikka 1i at t11
    r "You okay?"
    mc "Y-Yeah..."
    mc "I just..."
    "For some reason, I look back at Sayori's house."
    "Something is telling me I should go check on her even though she's sick."
    r 1g "[player]...?"
    mc "...Just a second. I think I'm gonna..."
    "Rikka seems to determine what I'm saying despite trailing off."
    r "Hey, I'm sure she's doing alright. Why don't we let her rest?"
    mc "I just... feel like I need to go see her right now."
    r 1e "{i}sight{/i} If you really want to, go ahead."
    r 1p "I'll wait out here for you."
    "I nod and go up to Sayori's front door."
    show rikka at thide
    hide rikka
    scene bg house
    with dissolve_scene_full
    pause 1.0
    scene black
    with dissolve_scene_full
    stop music fadeout 3.0
    $ s_name = "Sayori"
    "I let myself in, knowing she keeps her door unlocked for some reason."
    "{i}I really need to say something about that once she's feeling better.{/i}"
    "I make my way up to her room and knock on her door."
    mc "Sayori? It's me."
    mc "You uh... feeling better?"
    "..."
    "I don't hear any response."
    mc "Sorry for... y'know, bothering you while you're recovering."
    mc "Just wanted to see how you're doing."
    s "You don't h-have to apologize, silly."
    "She almost sounds like she's close to tears, but her voice is partially muffled by the door being closed."
    mc "Hey, are you okay?"
    s "I'm... yeah, I'm doing okay."
    mc "Oh... Um..."
    mc "Can I come in...?"
    s "I'm changing right now."
    mc "Oh! Crap, um..."
    mc "I didn't mean to-"
    mc "Ah...."
    s "It's okay."
    mc "Sorry, I'll go now."
    "I start walking away before I hear a loud noise muffled by the closed door."
    s "No, no! Don't go. Please."
    mc "...?"
    s "I know you've got school and all that, but..."
    s "I... I wanna ask you a question, [player]."
    mc "O...kay. What's up?"
    s "...Was I a good friend to you?"
    mc "What kinda question is that?"
    s "Just answer. I'm curious."
    mc "..."
    mc "You're the best I could ask for."
    s "Really?"
    mc "Of course. Why would I lie to you?"
    s "To spare my hurt feelings?"
    s "I dunno... I felt like..."
    s "I've always felt like I should've been better."
    mc "Hey, I've felt the same way a bunch of times."
    mc "Am I a good friend to you?"
    s "...The best."
    mc "I mean, there was that time I ignored you for like a whole few years and... you know..."
    s "It's okay. I'd have ignored me, too."
    mc "Why? Because I can tell you, personally, the reasons I had were really stupid."
    s "What were they?"
    "I chuckle lightly to myself before responding."
    mc "Well... they don't matter anymore."
    mc "What matters is that I realized how much I was missing by ignoring you."
    mc "Your laugh, your smile..."
    mc "Your clumsiness."
    "I can hear Sayori give a weak laugh."
    mc "... I missed my best friend."
    mc "It took me all that time to realize how much you mean to me."
    mc "And now I can't imagine going a day without you."
    mc "I... I love you, Sayori."
    s "{i}I love you, [player].{/i}"
    s "..."
    "I hear Sayori start crying behind the door."
    mc "What's wrong, Sayori?"
    "She doesn't answer me."
    "After a moment, I hear a thud come from inside her room."
    mc "Sayori? Are you okay??"
    "There's no answer."
    "I try to open the door, but it's locked."
    "I'm about to try and-"
    r "How can you even see anything in here?"
    "I jump at the sound of Rikka's voice right next to me."
    mc "I thought you were outside??"
    r "I was, but you've been in here for several minutes."
    r "So I wanted to see what you were-"
    mc "Nevermind. Sayori isn't answering me anymore and I just heard some kind of noise come from her room."
    r "That sound came from in there?"
    r "I heard it while I was trying to climb up the stairs just now."
    r "..."
    "She knocks on Sayori's door gently before speaking."
    r "Sayori, you okay? There was a-"
    "She cuts herself off."
    "It takes me a second to realize why, but I can barely hear a sound almost like a drawn-out squeak."
    "Suddenly, Rikka starts frantically trying to turn the door handle."
    mc "Hey, hey, calm down a-"
    "She jabs me in the side with her elbow, instantly shutting me up."
    mc "I feel like… that was unnecessary..."
    r "{i}She has a rope in her room.{/i}"
    mc "Huh? Why would..."
    mc "... Wait, you're not really suggesting-"
    r "Move away from the door."
    "I've never heard Rikka's voice sound this desperate before."
    "I oblige and step out of the way."
    "I can make out Rikka's figure standing directly in front of the door before turning a shoulder towards it."
    "She waits a moment, as if bracing herself, before ramming her shoulder into the door."
    "It opens immediately."
    "I don't even have time to process where that strength came from before I hear Rikka's voice again."
    r "Sayori... Sayori..."
    "I finally enter the room as..."
    scene bg sayori_bedroom_dark
    with dissolve_scene_half 
    mc "... What...?"
    #play music gnbun
    "Rikka is trying to hoise Sayori up..."
    "Sayori, who is hanging from a noose and trying to push Rikka away."
    "I force myself to move and do my best to help Rikka."
    "Somehow, we manage to get Sayori out of and away from the noose in the middle of her room."
    "Sayori is laying on her bed, gasping for air."
    mc "Sayori..."
    mc "W-Why... why did you-"
    "Sayori shakes her head weakly."
    "She slowly raises one of her arms and tries to point at something on her desk."
    r "You want something from your desk?"
    "Sayori tries to nod again but doesn't manage more than slightly moving her head up."
    "Rikka goes over to Sayori's desk while I try to process everything that's happening."
    "My best friend just tried to end her own life..."
    "... And if I hadn't listened to my gut, she would likely be dead right now."
    "I look into Sayori's eyes. They aren't shining like I've always known them to."
    "They look clouded by something."
    "I'm startled by Rikka, who returns to Sayori's bedside holding a piece of paper."
    "I can't see it that well, but it looks like a poem."
    r "You want us to read it?"
    "Sayori manages to hold her hand out."
    r "Oh, you want to read it?"
    "Sayori hesitates but manages another small nod."
    "Rikka smiles and hands Sayori the poem."
    mc "Here, I'll turn the light on so you can see it clearly."
    "I turn towards the light switch in the room."
    "Before I can reach the switch, I hear a soft gushing sound behind me."
    r "{i}Sayori!!{/i}"
    #play music pcut
    "I turn back around and see a pool of blood oozing from cuts in Sayori's neck."
    "The paper in her hand is bloody at the edge."
    "Once again, I can't make myself move to help her."
    "Rikka tries to put pressure on the wounds, but Sayori moves the paper towards her opposite arm."
    r "{i}[player], help me!!{/i}"
    "I have to practically use as much force as possible to bring myself to her bedside again."
    "There's now several cuts along her arm."
    "I try to cover them up with my hands, but they're spaced out too far apart to cover them all."
    "Rikka uses her other hand to cover the remaining cuts on her arm."
    "I realize a second too late that Sayori is about to take advantage of this opening."
    "She drops the paper and uses all of her strength to push away the hand on her neck's wound."
    "Before I can grab the paper, Sayori takes it..."
    "... and forces it back into one of the cuts in her neck."
    "I can't handle watching anymore and shut my eyes."
    "I try my best not to throw up and take a deep breath before opening my eyes again."
    "... Rikka's holding the paper in her hand."
    "She's crying silently as Sayori attempts to take any kind of breath."
    "All we can do now is watch helplessly as my best friend takes one last attempt at a breath."
    "Then she goes still."
    scene black with dissolve_scene_full
    #stop music fadeout 3.0
    pause 3.0
    "ACT II - Other Reality"